### ISSUE TITLE
Gitalk 无法加载

### ISSUE THREAD

**Issue by YooLc** [xyz60552/gridea#1]
未找到相关的 Issues 进行评论
请联系 @xyz60552 初始化创建

By the way,  这篇博文《[语文太难了...](https://xyz60552.github.io/post/lesslessne-han-greatergreater-zhong-de-kan-ke/)》使用超链接进入时，加密  js 会出现 bug ，如果能修复就太好了。

**Comment by xyz60552** [comment]
第一个应该好了.
第二个js bug我这里没有看到呀
发自我的 iPad 


| |
xyz
|
|
邮箱：xyz60552@163.com
|
在2020年08月06日 20:56，YooLc 写道：

未找到相关的 Issues 进行评论
请联系 @xyz60552 初始化创建

By the way, 这篇博文《语文太难了...》使用超链接进入时，加密 js 会出现 bug ，如果能修复就太好了。

**Comment by YooLc** [comment]
两个都没好啊>.<
我的系统环境：
- Windows 10 20.04
- Microsoft Edge 版本 84.0.522.52 (官方内部版本) (64 位)
